### ISSUE TITLE
Vite plugin

### ISSUE THREAD

**Issue by walmartwarlord** [facebook/stylex#47]
It would be nice to have a Vite plugin. I tried the rollup plugin with a fresh React + Vite and got an error:

```js
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import stylex from '@stylexjs/rollup-plugin'

export default defineConfig({
  plugins: [react(), stylex()],
})
```

Error: 

```bash
[vite] Internal server error: /Users/walmartwarlord/tmp/react-stylex-test/src/index.css: Unexpected token (1:0)

> 1 | :root {
    | ^
  2 |   font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  3 |   line-height: 1.5;
  4 |   font-weight: 400;
  Plugin: rollup-plugin-stylex
  File: /Users/walmartwarlord/tmp/react-stylex-test/src/index.css:1:0
  1  |  :root {
     |  ^
  2  |    font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  3  |    line-height: 1.5;
      at constructor (/Users/walmartwarlord/tmp/react-stylex-test/node_modules/.pnpm/@babel+parser@7.23.5/node_modules/@babel/parser/lib/index.js:356:19)
```

**Edit**: Cleaned up the fresh project; `dev` now runs successfully. However, running `build` leads to a different error.:

```tsx
import stylex from '@stylexjs/stylex'

const s = stylex.create({
  main: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 10,
    paddingTop: 20,
  }
})

function App() {
  return (
    <main className={stylex(s.main)}>
      <h1>Hello</h1>
    </main>
  )
}
```

```bash
vite v5.0.5 building for production...
✓ 0 modules transformed.
[rollup-plugin-stylex] /Users/walmartwarlord/tmp/react-stylex-test/index.html: Unexpected token (1:1)

> 1 | <!doctype html>
    |  ^
  2 | <html lang="en">
  3 |   <head>
  4 |     <meta charset="UTF-8" />
file: /Users/walmartwarlord/tmp/react-stylex-test/index.html:1:1
error during build:
SyntaxError: /Users/walmartwarlord/tmp/react-stylex-test/index.html: Unexpected token (1:1)

> 1 | <!doctype html>
    |  ^
  2 | <html lang="en">
  3 |   <head>
  4 |     <meta charset="UTF-8" />
    at constructor (/Users/walmartwarlord/tmp/react-stylex-test/node_modules/.pnpm/@babel+parser@7.23.5/node_modules/@babel/parser/lib/index.js:356:19)
```

**Comment by HorusGoul** [comment]
I encountered the same issue and put together a vite plugin based on the rollup plugin implementation: https://github.com/HorusGoul/vite-plugin-stylex

Install it with `npm install --save-dev vite-plugin-stylex` and use it like this:

```ts
// ... other imports

import styleX from "vite-plugin-stylex";

export default defineConfig({
  plugins: [react(), styleX()],
});
```

I haven't tried more complex use cases like SSR yet, but I guess we can add support for those as needed by users (already thinking of trying this with the new Remix Vite plugin)

---

**Question for maintainers**: Is there a plan for an official Vite plugin? Or is this expected to be covered by the community using lower-level plugins like the Babel one? Thanks!

**Comment by nmn** [comment]
We do want to support an official Vite plugin, but we want it to support "complex use cases like SSR" as well. This is important to us as many Vite projects like Remix, Qwik or the upcoming Solid-Start won't ship some components to the browser at all. Even in development.

We want our Vite plugin to work for these scenarios.

**Comment by HorusGoul** [comment]
@JakeSaterlay 

Depends on the complexity of the setup you're using, for example, my unofficial plugin doesn't support Astro or Qwik yet, but it will work with a basic create vite app that uses React (SPA) or even Remix using the unstable vite template.

**Comment by predaytor** [comment]
@HorusGoul, I am currently experimenting with `vite-plugin-styles` using Remix. But it seems that including `import 'virtual:stylex.css'` in `root.tsx` causes some problems.

In dev mode there is a duplication of styles with built-in styles from vite.
<img width="712" alt="Знімок екрана 2023-12-08 о 13 10 52" src="https://github.com/facebook/stylex/assets/32335730/54b21ac5-6dab-4e67-9205-c969aad9a01b">

In the production build, the `<head>` contains only one style reference (`root-I-XxiNSD.css`) but no stylex reference (`stylex.cdf3995e.css`).
<img width="712" alt="Знімок екрана 2023-12-08 о 13 10 12" src="https://github.com/facebook/stylex/assets/32335730/afb2d6c9-13b6-4ae5-99f1-6bcbc4c0eefd">


```bash
> vite build && vite build --ssr

vite v5.0.6 building for production...

  ⚠️  Remix support for Vite is unstable
     and not recommended for production

✓ 70 modules transformed.
public/build/.vite/manifest.json                0.89 kB │ gzip:  0.27 kB
public/build/assets/root-I-XxiNSD.css           0.45 kB │ gzip:  0.28 kB
public/build/assets/stylex.cdf3995e.css         2.84 kB │ gzip:  1.18 kB
public/build/assets/root-VHjyehqh.js            1.37 kB │ gzip:  0.81 kB
public/build/assets/jsx-runtime-NroC4D4D.js     8.09 kB │ gzip:  3.05 kB
public/build/assets/entry.client-Zz46Ypws.js    9.51 kB │ gzip:  3.73 kB
public/build/assets/_index-VynOg2Ww.js         11.95 kB │ gzip:  4.49 kB
public/build/assets/components-WD7OCPmZ.js    211.54 kB │ gzip: 68.46 kB
✓ built in 650ms
vite v5.0.6 building SSR bundle for production...

  ⚠️  Remix support for Vite is unstable
     and not recommended for production

1:07:08 PM [vite] page reload virtual:stylex.css
1:07:08 PM [vite] page reload virtual:stylex.css (x2)
1:07:08 PM [vite] page reload virtual:stylex.css (x3)
✓ 14 modules transformed.
1:07:08 PM [vite] page reload virtual:stylex.css
1:07:08 PM [vite] page reload virtual:stylex.css (x2)
build/.vite/manifest.json                         0.18 kB
build/assets/_virtual_server-entry-Whtg1KgZ.css   0.47 kB
build/assets/stylex.cdf3995e.css                  2.84 kB
build/index.js                                   12.16 kB
✓ built in 171ms
```

**Comment by nmn** [comment]
I worked with a team member from Qwik.js and have a Vite plugin working with it.
The code is a bit messy, but it all works. Probably worth trying to port over the same plugin and trying to make it work with Remix as well.

https://github.com/nmn/qwik-stylex

Important things to note:
- `vite.config.mjs`
- `vite-stylex-plugin/index.mjs`
- `root.tsx` contains `import "virtual:stylex.css";` which is required.

**Comment by nmn** [comment]
On my end, I'm going to try and it make it work with Svelte.

**Comment by nonzzz** [comment]
Any upates. I created a repo to record the progress of the vite plugin.

https://github.com/nonzzz/vite-plugin-stylex

CheckList

- [x] Add remix and qwik demo
- [ ] unit test case
- [ ] Make logic better

It's work well for those demo. But i can't balance some designs like should we need fileName option? AFAK. vite can already handle css internally. So we only set a virtual module for eacth entry is enough.
And then in production mode we only update the renderChunk vite will collect all of styles and do the rest.

@nmn

**Comment by nmn** [comment]
I have a Vite plugin that's working with Qwik and Svelte on my end that doesn't rely on renderChunk etc. I worked on people from the Qwik team and got it to work. It worked in Svelte without many tweaks. 

https://github.com/nmn/sveltekit-stylex

It shouldn't need a `fileName` arg IMO.

**Comment by predaytor** [comment]
@nmn, is there any time frame when we can expect an official adapter for Vite? Thx

**Comment by nmn** [comment]
@predaytor You're welcome to use the one from https://github.com/nmn/sveltekit-stylex if you want. Other than that, I don't have any timelines for you. When I feel confident in an implementation, we will add it to the repo. Don't let stop you from using it in the meantime.

**Comment by berkgulmus** [comment]
Anyone interested in using StyleX in Vue3? I've tried @HorusGoul 's vite plugin and although it compiles without error, I couldn't get it to work. Are there gonna be official support for all major frameworks in the future?

**Comment by nonzzz** [comment]
@berkgulmus see https://github.com/facebook/stylex/discussions/154 . I have implemented a version and am currently preparing unit tests and e2e tests.

**Comment by I-NOZex** [comment]
NUXT 3 + Vite usage example: https://stackblitz.com/edit/nuxt-3-vite-stylex
Vue 3 + Vite usage example: https://stackblitz.com/edit/vue-3-vite-stylex

**Comment by YokasCarbon** [comment]
qww

**Comment by pravintargaryen** [comment]
@HorusGoul's solution works for vite

**Comment by MentorAliu** [comment]
@HorusGoul  solution works, rollup-plugin however not working on Vite

**Comment by nmn** [comment]
I haven't had time to look at the implementation of the Vite plugin by @HorusGoul but people have been generally happy with it.

Once we verify that it works in all the scenarios we care about, we can start recommending it officially. The community can do a better job at this than us trying to understand the idiosyncrasies of each bundler!

**Comment by zaydek** [comment]
I tried @HorusGoul's `vite-plugin-stylex` version and it didn't work for me in production, only development (missing styles, tried about a week ago). I've been using @nonzzz's `vite-plugin-stylex-dev` since and it hasn't given me any problems. Sometimes the app appears before the styles are ready but if I reload it works. I haven't had any issues with it working in production.

I'm sure this comment won't be relevant long term but it's worth stating that if Stylex doesn't work with one plugin doesn't mean that it doesn't work in general. Like @nmn Bundlers and dev servers are very idiosyncratic said so just try a few. I'm sure they'll all converge on working solutions anyway.

**Comment by movahhedi** [comment]
@zaydek I've experienced it too. I figured it's because it doesn't set the path correctly in the HTML. Check [vite-plugin-stylex#28](https://github.com/HorusGoul/vite-plugin-stylex/issues/28)

**Comment by nmn** [comment]
@zaydek @movahhedi Did you try the using the plugin as written in the Qwik and Svelte examples I shared above?

- https://github.com/nmn/qwik-stylex
- https://github.com/nmn/sveltekit-stylex

I don't want to publish an official package until I can verify that this approach works in a wide range scenarios. Vite is so popular that it is used in many different ways. However, since the approach works in Qwik which has many of the same characteristics as RSCs I'm hopeful it can work in most cases.

**Comment by edamascus** [comment]
I used `vite-plugin-stylex` v0.4.1 with a React spa project with Vite and it worked successfully in dev and production.

However, since I updated StyleX to v0.4.1, I am getting the following error: `Uncaught TypeError: stylex.inject is not a function`, not sure if this is related to the plugin or to something else with the new package. I have tried the same setup on a new project from scratch but it also failed. I also tried clearing Vite cache.

Trying to use the official `@stylexjs/babel-plugin` and `@stylexjs/rollup-plugin` without `vite-plugin-stylex` did not work from the beginning.

**Comment by zaydek** [comment]
> @zaydek @movahhedi Did you try the using the plugin as written in the Qwik and Svelte examples I shared above?
> 
> * https://github.com/nmn/qwik-stylex
> * https://github.com/nmn/sveltekit-stylex
> 
> I don't want to publish an official package until I can verify that this approach works in a wide range scenarios. Vite is so popular that it is used in many different ways. However, since the approach works in Qwik which has many of the same characteristics as RSCs I'm hopeful it can work in most cases.

@nmn Is your Vite plugin implementation published to NPM, even as a beta or alpha release? You can release the version namespaced with alpha or beta or canary if you like. I'd be happy to give feedback on that. I'm just using React (CSR style) but I am using Vite.

**Comment by nonzzz** [comment]
> used `vite-plugin-stylex` v0.4.1 with a React spa project with Vite and it worked successfully in dev and production.
> 
> However, since I updated StyleX to v0.4.1, I am getting the following error: `Uncaught TypeError: stylex.inject is not a function`, not sure if this is related to the plugin or to something else with the new package. I have tried the same setup on a new project from scratch but it also failed. I also tried clearing Vite cache.
> 
> Trying to use the official `@stylexjs/babel-plugin` and `@stylexjs/rollup-plugin` without `vite-plugin-stylex` did not work from the beginning.

I think maybe esm cause it.I am currently looking for a better way to balance between multiple frameworks

**Comment by nonzzz** [comment]
I will test esm after this weekend.

**Comment by zaydek** [comment]
> I will test esm after this weekend.

Just wanted to say thanks. Your plugin has been working nearly perfectly for me.

**Comment by nmn** [comment]
> Is your Vite plugin implementation published to NPM, even as a beta or alpha release?

Not yet. I'm testing a few more frameworks before I do this.

> Alternatively do you have a React example I should install from GitHub instead?

I don't have a React example, you should be able to copy the setup from the Qwik example to try it with a React app.

**Comment by zaydek** [comment]
> > Is your Vite plugin implementation published to NPM, even as a beta or alpha release?
> 
> Not yet. I'm testing a few more frameworks before I do this.
> 
> > Alternatively do you have a React example I should install from GitHub instead?
> 
> I don't have a React example, you should be able to copy the setup from the Qwik example to try it with a React app.

Yes, can try once I start a project tabula rasa that uses Stylex.

**Comment by nonzzz** [comment]
@zaydek A friendly ping i release `v0.2.1` for my plugin. In this version i support path alias and convert most of hmr scenes and upgrate `stylexjs` deps. I will verify astro and SvelteKit soon

**Comment by zaydek** [comment]
> > Is your Vite plugin implementation published to NPM, even as a beta or alpha release?
> 
> Not yet. I'm testing a few more frameworks before I do this.
> 
> > Alternatively do you have a React example I should install from GitHub instead?
> 
> I don't have a React example, you should be able to copy the setup from the Qwik example to try it with a React app.

@nmn I tried to create a repro using React based on the Qwik directory you shared but I crashed and burned pretty quickly. Here is the rerpo repo: https://github.com/zaydek/experimental-vite-stylex-official. It's very possible I did something wrong but I tried to take the Qwik code base and just make the necesarry changes to React, nothing else.

<img width="678" alt="Screenshot 2024-01-11 at 4 24 11 AM" src="https://github.com/facebook/stylex/assets/58870766/d9816c46-067e-4e82-bbd4-a0e99d1cc093">

```
zaydek@Zaydeks-MacBook-Pro experimental-vite-stylex-official % npx vite dev
Re-optimizing dependencies because lockfile has changed

  VITE v5.0.11  ready in 278 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  Inspect: http://localhost:5173/__inspect/
  ➜  press h + enter to show help
4:23:10 AM [vite] hmr update /src/App.tsx
✘ [ERROR] Could not resolve "./StyleXSheet"

    node_modules/@stylexjs/stylex/lib/es/stylex-inject.mjs:1:27:
      1 │ import { styleSheet } from './StyleXSheet';
        ╵                            ~~~~~~~~~~~~~~~

4:23:10 AM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@stylexjs/stylex/lib/es/stylex-inject.mjs:1:27: ERROR: Could not resolve "./StyleXSheet"
    at failureErrorWithLog (/Users/zaydek/Code/__corpo/experimental-vite-stylex-official/node_modules/esbuild/lib/main.js:1651:15)
    at /Users/zaydek/Code/__corpo/experimental-vite-stylex-official/node_modules/esbuild/lib/main.js:1059:25
    at /Users/zaydek/Code/__corpo/experimental-vite-stylex-official/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by zaydek** [comment]
> @zaydek A friendly ping i release `v0.2.1` for my plugin. In this version i support path alias and convert most of hmr scenes and upgrate `stylexjs` deps. I will verify astro and SvelteKit soon

Thank you! Still no problems. I've been succesfully ship two project so far using Stylex and vite-plugin-stylex-dev.

I think you may have fixed the problem where the stylesheet doesn't load initially (seems to happen once when I start working on a project, then goes away indefinitely) because I can't reproduce it anymore.

**Comment by nmn** [comment]
@zaydek Can you check if v0.5.0-alpha.3 fixes this problem?

See #346 for the change made.

**Comment by zaydek** [comment]
> @zaydek Can you check if v0.5.0-alpha.3 fixes this problem?
> 
> See #346 for the change made.

Thanks OK. @nmn few observations:

When upgrading all Stylex-related packages to `v0.5.0-alpha.3` and building in dev mode, I first see this error:

<img width="1224" alt="Screenshot 2024-01-12 at 4 46 23 PM" src="https://github.com/facebook/stylex/assets/58870766/9ff9b651-a5ac-4ce5-8621-bb34341fa026">

Packages upgraded in question:

```
"@stylexjs/stylex": "^0.5.0-alpha.3",
"@stylexjs/babel-plugin": "^0.5.0-alpha.3",
"@stylexjs/eslint-plugin": "^0.5.0-alpha.3",
```

So I went into the `src/vite-stylex-plugin` file and exclusively commented out  these lines:

```
//// import { babelPluginTailwindToStylex } from "tailwind-to-stylex";
...
          //// babelPluginTailwindToStylex(),
```

One I did that both npx vite dev and npx vite build && npx vite preview (production mode) started working. There was one thing I noticed in the production console logs:

<img width="513" alt="Screenshot 2024-01-12 at 4 47 04 PM" src="https://github.com/facebook/stylex/assets/58870766/2ac92ac3-f0ea-4188-a653-5c75bffb8cde">

You can ignore the locator stuff that's a Chrome plugin. To sanity check I opened it in Incognito mode and I see the same error. And if I click on where `virtual:stylex.css:1` links to in the console I see this:

<img width="347" alt="Screenshot 2024-01-12 at 4 51 41 PM" src="https://github.com/facebook/stylex/assets/58870766/9e46edf3-601d-4dec-94ae-d15b7e5d8172">

So it looks like it's very close to working without caveats, the naunces being the Tailwind thing (which doesn't seem necesarry for this plugin) and the superfluous console error which doesn't prevent the styles from being applied.

Let me know when you want me to test again. The reference repo is up to date with this comment as of now.

**Comment by nmn** [comment]
> the naunces being the Tailwind thing (which doesn't seem necesarry for this plugin)

This has already been removed the `qwik-stylex` repo and moved into a separate plugin. That's unrelated to StyleX.

----

The `virtual:stylex.css` is an interesting case which works sometimes. This feels like the main issue with the Vite plugin at the moment.

----

You can remove the `pre` plugin entirely from your vite config. That is a separate plugin that allows using Tailwind by converting it to stylex. It's completely unrelated to StyleX and the Vite plugin.

----

> One I did that both npx vite dev and npx vite build && npx vite preview (production mode) started working.

This is the main thing I needed right now, since I'm trying to make the neccessary changes to StyleX itself. Thanks for the confirmation. I will go ahead with the StyleX changes and will revisit the Vite plugin to fix the `virtual:stylex.css` issue.

**Comment by nonzzz** [comment]
> > the naunces being the Tailwind thing (which doesn't seem necesarry for this plugin)
> 
> This has already been removed the `qwik-stylex` repo and moved into a separate plugin. That's unrelated to StyleX.
> 
> The `virtual:stylex.css` is an interesting case which works sometimes. This feels like the main issue with the Vite plugin at the moment.
> 
> You can remove the `pre` plugin entirely from your vite config. That is a separate plugin that allows using Tailwind by converting it to stylex. It's completely unrelated to StyleX and the Vite plugin.
> 
> > One I did that both npx vite dev and npx vite build && npx vite preview (production mode) started working.
> 
> This is the main thing I needed right now, since I'm trying to make the neccessary changes to StyleX itself. Thanks for the confirmation. I will go ahead with the StyleX changes and will revisit the Vite plugin to fix the `virtual:stylex.css` issue.

I think vite plugin don't need inject style logic because vite has own hmr logic so we only keep them work it's enough, The most of thing is esm package should be work fine. By the way order is unnecessary. Normally `pre` is alway work for parse unknown things. The above opinions represent only my own

**Comment by johnsonav1992** [comment]
I followed the instructions exactly for `vite-stylex-plugin` and I am still getting the error: "stylex.create should never be called. It should be compiled away."

Any reason why?

![image](https://github.com/facebook/stylex/assets/97169070/a1b2e4cc-bce4-4c25-af78-c6d83c0f4979)

**Comment by HorusGoul** [comment]
@johnsonav1992 try with this import:

```tsx
import * as stylex from '@stylexjs/stylex';
```

idk why but using the named export doesn't work with the plugin

**Comment by nmn** [comment]
@johnsonav1992 

`import {stylex} from` is not supported. The named export was a mistake and will be removed in the next release. 

Both `import stylex from` and `import * as stylex` should work though.

**Comment by johnsonav1992** [comment]
@nmn @HorusGoul Yep, that worked! I do find it odd that they aren't allowing a named export but I'm assuming it's because of stuff under the hood that doesn't allow everything to work properly. Thanks again!

**Comment by necolas** [comment]
@nmn Let's close this old issue. I don't think we'll develop or maintain more bundler plugins

**Comment by movahhedi** [comment]
Vite is already the go-to for many.

It's sad that we can't use Stylex.

Webpack is like WordPress: old, boring, but widespread.

**Comment by necolas** [comment]
This thread is full of options to use stylex with vite. The plugin just won't be maintained out of this repo, and anyone who is experienced with developing vite plugins can integrate the stylex transform

**Comment by nmn** [comment]
Closing this issue for now as the recommendation is to use one of the two community Vite plugins.

We might work on a Vite plugin eventually, but we have higher priority tasks to tackle in the short and medium term.

**Comment by mpstaton** [comment]
FYI, I've been arguing with my code for several hours now over this issue. I've tried several of the plugins discussed here.  None work. I will try unplugin but implementing it is going to be a bitch.  

Is there an alternative to Vite that handles Stylex better? 


vite v5.4.14 building for production...
src/components/YouTubeResponseViewer.tsx (2:31): "inject" is not exported by "../../node_modules/.pnpm/@stylexjs+stylex@0.9.3/node_modules/@stylexjs/stylex/lib/es/stylex.mjs", imported by "src/components/YouTubeResponseViewer.tsx".
src/components/YouTubeResponseViewer.tsx (2:31): "inject" is not exported by "../../node_modules/.pnpm/@stylexjs+stylex@0.9.3/node_modules/@stylexjs/stylex/lib/es/stylex.mjs", imported by "src/components/YouTubeResponseViewer.tsx".
src/components/YouTubeResponseViewer.tsx (2:31): "inject" is not exported by "../../node_modules/.pnpm/@stylexjs+stylex@0.9.3/node_modules/@stylexjs/stylex/lib/es/stylex.mjs", imported by "src/components/YouTubeResponseViewer.tsx".
src/components/YouTubeResponseViewer.tsx (2:31): "inject" is not exported by "../../node_modules/.pn

**Comment by zaydek** [comment]
@mpstaton I've used both:

- https://github.com/HorusGoul/vite-plugin-stylex
- https://github.com/nonzzz/vite-plugin-stylex

It looks like the second one is now archived `vite-plugin-stylex-dev` but I had some problems with it anyway because it didn't have caching at the time.

`vite-plugin-stylex` has worked consistently and reliably. Only nuance is including the `@stylex` thing correctly.

Do you mind sharing your `package.json` and `vite.config.ts`?

**Comment by mpstaton** [comment]
@zaydek here's the whole code, it's public: https://github.com/mpstaton/grab-reference
The branch that is bugging out is pushed as 'stalled-ui'

I don't seem to have a vite.config at the root?  Is that a problem?  

```package.json
{
  "name": "citation-manager",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev:web": "pnpm --filter @citation-manager/web dev",
    "dev:api": "pnpm --filter @citation-manager/citation-service dev",
    "dev": "pnpm -r dev",
    "build": "pnpm -r build",
    "test": "pnpm -r test",
    "lint": "pnpm -r lint",
    "db:generate": "pnpm --filter @citation-manager/citation-service prisma:generate",
    "db:migrate": "pnpm --filter @citation-manager/citation-service prisma:migrate",
    "docker:build": "docker build -t citation-manager .",
    "docker:run": "docker run -p 3000:3000 -p 8080:8080 citation-manager",
    "start:web": "pnpm --filter @citation-manager/web start",
    "start:api": "pnpm --filter @citation-manager/citation-service start",
    "start": "pnpm -r --parallel start"
  },
  "devDependencies": {
    "eslint": "^8.56.0",
    "prettier": "^3.1.1",
    "typescript": "^5.3.3"
  },
  "packageManager": "pnpm@10.4.1+sha512.c753b6c3ad7afa13af388fa6d808035a008e30ea9993f58c6663e2bc5ff21679aa834db094987129aa4d488b86df57f7b634981b2f827cdcacc698cc0cfb88af",
  "dependencies": {
    "@types/dotenv": "^8.2.3",
    "dotenv": "^16.4.7"
  }
}
```vite.config.js
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import styleX from '@stylexjs/rollup-plugin';

export default defineConfig({
  plugins: [react(), styleX({
    dev: true,
    runtimeInjection: true,
    styleResolution: 'application-order'
  })],
  server: {
    port: 5173,
    host: true,
    watch: {
      usePolling: true
    }
  },
  preview: {
    port: 5173,
    host: true
  }
});


```

**Comment by nmn** [comment]
@mpstaton I think your repo is private and I'm getting a 404 when I try to see it.

**Comment by nonzzz** [comment]
Since there's already a PostCSS plugin available, we can keep it simple. Just need a basic Vite wrapper and use the transform Hook without worrying about HMR since Vite+PostCSS can handle the resource management.

Off-topic: For the farmfe work I'm focusing on, PostCSS really helps streamline things. Just need to keep JS quiet during transform and we're good. And the reason I archived it is because I want to put it in `stylex-extend`

For `farmfe` 

Just a simple case

```ts

function stylex() {
  return <JsPlugin>{
    name: 'stylex',
    transform: {
      filters: {
        moduleTypes: ['ts', 'tsx']
      },
      executor(param) {
        if (
          param.resolvedPath === 'farmfe_plugin_react_is_react_refresh_boundary'
        ) {
          return param;
        }
        const plugins: ParserOptions['plugins'] = ['typescript'];
        if (param.resolvedPath.endsWith('.tsx')) {
          plugins.push('jsx');
        }
        const res = transform(param.content, {
          filename: param.resolvedPath,
          parserOpts: {
            plugins
          },
          plugins: [
            stylexExtendBabelPlugin.withOptions({
              unstable_moduleResolution: {
                type: 'commonJS',
                rootDir: __dirname
              },
              transport: 'props'
            }),
            stylexBabelPlugin.withOptions({
              dev: false,
              runtimeInjection: false,
              unstable_moduleResolution: {
                type: 'commonJS',
                rootDir: __dirname
              }
            })
          ]
        });
        if (res && 'stylex' in res.metadata) {
          if (
            Array.isArray(res.metadata.stylex) &&
            res.metadata.stylex.length > 0
          ) {
            return {
              content: res.code,
              sourceMap: res?.map,
              moduleType: 'tsx',
              ignorePreviousSourceMap: true
            };
          }
        }
        return param;
      }
    }
  };
}


```

And then using postcss plugin pipeline :D  I hope it can be helpful.

**Comment by nonzzz** [comment]
Different with [vite-plugin-stylex](https://github.com/HorusGoul/vite-plugin-stylex). [@stylex-extend/vite](https://github.com/nonzzz/stylex-extend/tree/master/packages/vite) has implemented some magic RFC. Like `JSXAttribute`support.  define `inline` style. About integrate, i'll do some work at the weekend migrate to postcss pipeline. ( No need fight with vite hmr :D)

**Comment by nmn** [comment]
The PostCSS plugin makes adoption a lot easier and is a lot less complicated than a Vite plugin. Rollup is one of the best bundlers but Vite does many weird things, specially in dev mode.

I'm hoping Rolldown solves many of these issues.

**Comment by nonzzz** [comment]
HMR is complicated incorrect updates can easily cause tdz. It should be noted that `postcss` plugin is a scanner to record your application and don't using vite internal file system so you should make sure keep js/ts and etc be quiet during vite transform stage. For integrater

```ts

{
 // ...
 async transform(code, id) {
  if (id.includes('/node_modules/')) { return }
  const res = await babel.transformAsync(code, {
     // the same option with your postcss config about stylex. 
    // don't forget put stylex babel plugin here.
  })
  // and return the transform result 
 }
}

```

The above are some ideas, have fun

**Comment by hrasoa** [comment]
I'm using the postcss plugin, it works very well and it's easy to setup.

**Comment by predaytor** [comment]
@hrasoa but is it possible to use lightningcss for minification then?
